# Generated by Django 5.2.15 on 2026-08-06 05:15
#
# Hand-edited after generation for three reasons:
#
# 1. Operation order. The generator emitted RemoveField(default_billing_mode)
#    first, which would have destroyed the data the back-fill needs. The removal
#    now runs last, after the new column has been populated from the old one.
# 2. The seed and back-fill RunPython step was added.
# 3. The reverse direction re-derives default_billing_mode from the new foreign
#    key, so this migration is genuinely reversible rather than merely
#    un-appliable. Reversal is lossy only for clients whose default is a billing
#    type that the old two-value enum could not express; see the note there.

import django.core.validators
import django.db.models.deletion
import plane.db.mixins
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

from plane.utils.service_catalog_seed import (
    LEGACY_BILLING_MODE_TO_TYPE_NAME,
    seed_service_catalogs,
)


def seed_catalogues_and_backfill_client_default(apps, schema_editor):
    """Give every existing workspace the initial catalogues, then move the client
    default from the removed enum onto the new foreign key."""
    Workspace = apps.get_model("db", "Workspace")
    ServiceHourType = apps.get_model("db", "ServiceHourType")
    ServiceBillingType = apps.get_model("db", "ServiceBillingType")
    ServiceClient = apps.get_model("db", "ServiceClient")

    workspace_ids = list(Workspace.objects.filter(deleted_at__isnull=True).values_list("id", flat=True))

    for workspace_id in workspace_ids:
        seed_service_catalogs(ServiceHourType, ServiceBillingType, workspace_id)

        billing_type_ids_by_name = dict(
            ServiceBillingType.objects.filter(workspace_id=workspace_id, deleted_at__isnull=True).values_list(
                "name", "id"
            )
        )

        for legacy_value, billing_type_name in LEGACY_BILLING_MODE_TO_TYPE_NAME.items():
            billing_type_id = billing_type_ids_by_name.get(billing_type_name)

            if billing_type_id is None:
                continue

            # all_objects equivalent: the historical manager is unfiltered, so soft
            # deleted clients are updated too. That is wanted -- a client that is
            # later restored must not come back with an unset default.
            ServiceClient.objects.filter(
                workspace_id=workspace_id, default_billing_mode=legacy_value
            ).update(default_billing_type_id=billing_type_id)


def restore_client_billing_mode(apps, schema_editor):
    """Reverse: put the enum value back, derived from the billing type.

    Runs after RemoveField has been reversed, so the column exists again and every
    row holds its 'contract' default. Only the rows that should read 'ad_hoc' need
    touching.

    Lossy in one direction that cannot be helped: a client whose default is
    Garantia, Cortesia or an admin-created billing type has no equivalent in a
    two-value enum, and keeps the 'contract' default. Recorded here rather than
    silently ignored.
    """
    ServiceClient = apps.get_model("db", "ServiceClient")
    ServiceBillingType = apps.get_model("db", "ServiceBillingType")

    legacy_value_by_name = {name: value for value, name in LEGACY_BILLING_MODE_TO_TYPE_NAME.items()}

    for billing_type_id, billing_type_name in ServiceBillingType.objects.values_list("id", "name"):
        legacy_value = legacy_value_by_name.get(billing_type_name)

        if legacy_value is None:
            continue

        ServiceClient.objects.filter(default_billing_type_id=billing_type_id).update(
            default_billing_mode=legacy_value
        )


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0123_service_client_and_project_service_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceBillingType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("sequence", models.FloatField(default=65535)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("external_source", models.CharField(blank=True, max_length=255, null=True)),
                ("external_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "billing_route",
                    models.CharField(
                        choices=[
                            ("debit_pool", "Debit hour pool"),
                            ("bill_amount", "Bill amount"),
                            ("non_billable", "Non billable"),
                        ],
                        default="debit_pool",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Billing Type",
                "verbose_name_plural": "Service Billing Types",
                "db_table": "service_billing_types",
                "ordering": ("sequence",),
                "abstract": False,
            },
            bases=(plane.db.mixins.ChangeTrackerMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ServiceHourType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("sequence", models.FloatField(default=65535)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("external_source", models.CharField(blank=True, max_length=255, null=True)),
                ("external_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=4,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("color", models.CharField(default="#60646C", max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Hour Type",
                "verbose_name_plural": "Service Hour Types",
                "db_table": "service_hour_types",
                "ordering": ("sequence",),
                "abstract": False,
            },
            bases=(plane.db.mixins.ChangeTrackerMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ServiceConfigActivity",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("entity_name", models.CharField(max_length=255)),
                ("entity_identifier", models.UUIDField()),
                ("field_name", models.CharField(max_length=255)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_config_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Config Activity",
                "verbose_name_plural": "Service Config Activities",
                "db_table": "service_config_activities",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="servicebillingtype",
            index=models.Index(fields=["workspace", "is_active"], name="svc_billing_type_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="servicebillingtype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("workspace", "name"),
                name="servicebillingtype_unique_name_workspace_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicebillingtype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("is_default", True)),
                fields=("workspace",),
                name="servicebillingtype_single_default_per_workspace",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="servicebillingtype",
            unique_together={("workspace", "name", "deleted_at")},
        ),
        migrations.AddIndex(
            model_name="servicehourtype",
            index=models.Index(fields=["workspace", "is_active"], name="svc_hour_type_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="servicehourtype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("workspace", "name"),
                name="servicehourtype_unique_name_workspace_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicehourtype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("is_default", True)),
                fields=("workspace",),
                name="servicehourtype_single_default_per_workspace",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="servicehourtype",
            unique_together={("workspace", "name", "deleted_at")},
        ),
        migrations.AddIndex(
            model_name="serviceconfigactivity",
            index=models.Index(
                fields=["workspace", "entity_name", "entity_identifier", "created_at"],
                name="svc_cfg_activity_entity_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="serviceconfigactivity",
            index=models.Index(fields=["workspace", "-created_at"], name="svc_cfg_activity_recent_idx"),
        ),
        migrations.AddField(
            model_name="serviceclient",
            name="default_billing_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="service_clients",
                to="db.servicebillingtype",
            ),
        ),
        # Runs while both columns exist: the catalogues have to be seeded before a
        # client can point at one, and default_billing_mode has to survive until it
        # has been read.
        migrations.RunPython(
            seed_catalogues_and_backfill_client_default,
            reverse_code=restore_client_billing_mode,
        ),
        migrations.RemoveField(
            model_name="serviceclient",
            name="default_billing_mode",
        ),
    ]
