# Generated by Django 5.2.15 on 2026-08-06 12:47
#
# Purely additive: one new table, no data migration and no back-fill, so the reverse
# is a plain DROP TABLE and this migration is genuinely reversible.
#
# Validated by hand, because pytest.ini sets --nomigrations and the suite therefore
# builds its schema from the models and would not notice if this file were broken.
#
# Three things a reviewer is likely to want to change, and should not:
#
# 1. `hour_type`, `billing_type`, `suggested_hour_type` and `author` are DO_NOTHING.
#    PROTECT is the intuitive choice and is a data-loss path in this codebase:
#    plane.bgtasks.deletion_task.soft_delete_related_objects branches on the
#    on_delete name, and PROTECT has no branch of its own, so it falls into the same
#    catch-all as CASCADE and soft deletes the related rows. An admin tidying the
#    hour type catalogue would silently soft delete work logs. SET_NULL would strip
#    the historical label instead. See the comments on the model.
# 2. `issue` is CASCADE, and that inconsistency is deliberate -- a work log has no
#    meaning without its work item. Also documented on the model.
# 3. The three CheckConstraints are the first in this repository. They encode the
#    rules that decide what a client is charged, in DDL, so that no future queryset
#    .update() or data migration can bypass them.

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_service_catalog_and_config_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_hour_type_overridden', models.BooleanField(default=False)),
                ('classification_reason', models.CharField(blank=True, max_length=255)),
                ('worked_on', models.DateField()),
                ('description', models.TextField()),
                ('entry_mode', models.CharField(choices=[('duration', 'Free text duration'), ('interval', 'Start and end time')], default='duration', max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Entered by hand'), ('imported', 'Migrated from another system'), ('api', 'Created through the API')], default='manual', max_length=20)),
                ('raw_duration_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('logged_hours', models.DecimalField(decimal_places=4, max_digits=10)),
                ('equivalent_hours', models.DecimalField(decimal_places=4, max_digits=10)),
                ('debited_hours', models.DecimalField(decimal_places=4, max_digits=10)),
                ('applied_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('applied_billing_route', models.CharField(choices=[('debit_pool', 'Debit hour pool'), ('bill_amount', 'Bill amount'), ('non_billable', 'Non billable')], default='debit_pool', max_length=20)),
                ('batch_id', models.UUIDField(db_index=True)),
                ('segment_index', models.PositiveSmallIntegerField(default=0)),
                ('external_source', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_logs', to=settings.AUTH_USER_MODEL)),
                ('billing_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_logs', to='db.servicebillingtype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('hour_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_logs', to='db.servicehourtype')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('suggested_hour_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='suggested_service_logs', to='db.servicehourtype')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Service Log',
                'verbose_name_plural': 'Service Logs',
                'db_table': 'service_logs',
                'ordering': ('-worked_on', '-created_at'),
                'indexes': [models.Index(fields=['issue', '-worked_on'], name='service_log_issue_worked_idx'), models.Index(fields=['project', 'worked_on'], name='service_log_project_worked_idx'), models.Index(fields=['workspace', 'worked_on'], name='service_log_ws_worked_idx'), models.Index(fields=['author', 'worked_on'], name='service_log_author_worked_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('batch_id', 'segment_index'), name='service_log_unique_batch_segment_when_deleted_at_null'), models.CheckConstraint(condition=models.Q(('raw_duration_minutes__gte', 1)), name='service_log_raw_duration_is_positive'), models.CheckConstraint(condition=models.Q(models.Q(('end_time__isnull', True), ('entry_mode', 'duration'), ('start_time__isnull', True)), models.Q(('end_time__isnull', False), ('entry_mode', 'interval'), ('start_time__isnull', False)), _connector='OR'), name='service_log_entry_mode_matches_times'), models.CheckConstraint(condition=models.Q(models.Q(('applied_billing_route', 'non_billable'), ('debited_hours', 0)), models.Q(models.Q(('applied_billing_route', 'non_billable'), _negated=True), ('debited_hours', models.F('equivalent_hours'))), _connector='OR'), name='service_log_debited_hours_follows_billing_route')],
                'unique_together': {('batch_id', 'segment_index', 'deleted_at')},
            },
        ),
    ]
