# Generated by Django 5.2.15 on 2026-08-06 14:21
#
# Hand-edited to add the data step at the end: back-fill `priority` on the hour types
# that already exist, then seed the classification windows that express rule R10.
#
# Validated by hand, because pytest.ini sets --nomigrations and the suite builds its
# schema from the models -- a broken migration would not fail a single test.
#
# THE BACK-FILL IS DELIBERATELY TOLERANT. It matches hour types by name, and a name
# that does not match is left at the model default (1000) instead of raising. An
# installation where an admin renamed "Fora do expediente" must still be able to
# migrate: a wrong priority is a value to fix in the panel, while a migration that
# refuses to apply is an outage. Same reasoning for the window seeding below.

import django.core.validators
import django.db.models.deletion
import plane.db.mixins
import uuid
from django.conf import settings
from django.db import migrations, models

from plane.utils.service_catalog_seed import HOUR_TYPE_SEED, seed_classification_windows


def backfill_priorities_and_seed_windows(apps, schema_editor):
    """Give existing hour types their priority, then seed the windows of every workspace."""
    ServiceHourType = apps.get_model("db", "ServiceHourType")
    ServiceClassificationWindow = apps.get_model("db", "ServiceClassificationWindow")
    Workspace = apps.get_model("db", "Workspace")

    priority_by_name = {row["name"]: row["priority"] for row in HOUR_TYPE_SEED}

    for name, priority in priority_by_name.items():
        # Only the seeded names are touched. Anything else -- renamed, or created by an
        # admin -- keeps the model default and is inert until it is given a window,
        # because an hour type with no window is never suggested.
        ServiceHourType.objects.filter(name=name).update(priority=priority)

    workspace_ids = list(Workspace.objects.filter(deleted_at__isnull=True).values_list("id", flat=True))

    for workspace_id in workspace_ids:
        seed_classification_windows(ServiceClassificationWindow, ServiceHourType, workspace_id)


def clear_windows(apps, schema_editor):
    """Reverse of the data step.

    Only the windows are removed; `priority` disappears with its column, so there is
    nothing to undo there. Reversal is lossy for windows an admin added by hand, which
    is unavoidable -- there is no way to tell them from the seeded ones, and leaving
    them behind would orphan rows pointing at a table that is about to be dropped.
    """
    ServiceClassificationWindow = apps.get_model("db", "ServiceClassificationWindow")
    ServiceClassificationWindow.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0125_service_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceClassificationWindow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('day_scope', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('holiday', 'Holiday')], max_length=20)),
                ('start_minute', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1439)])),
                ('end_minute', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Classification Window',
                'verbose_name_plural': 'Service Classification Windows',
                'db_table': 'service_classification_windows',
                'ordering': ('day_scope', 'start_minute'),
            },
            bases=(plane.db.mixins.ChangeTrackerMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceHoliday',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('scope', models.CharField(choices=[('national', 'National'), ('state', 'State'), ('municipal', 'Municipal')], default='national', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('external_source', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Service Holiday',
                'verbose_name_plural': 'Service Holidays',
                'db_table': 'service_holidays',
                'ordering': ('date', 'name'),
            },
            bases=(plane.db.mixins.ChangeTrackerMixin, models.Model),
        ),
        migrations.AddField(
            model_name='servicehourtype',
            name='priority',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddIndex(
            model_name='servicehourtype',
            index=models.Index(fields=['workspace', 'priority'], name='svc_hour_type_priority_idx'),
        ),
        migrations.AddField(
            model_name='serviceclassificationwindow',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='serviceclassificationwindow',
            name='hour_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='windows', to='db.servicehourtype'),
        ),
        migrations.AddField(
            model_name='serviceclassificationwindow',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='serviceclassificationwindow',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='serviceclassificationwindow',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='serviceholiday',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='serviceholiday',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='serviceholiday',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='serviceholiday',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddIndex(
            model_name='serviceclassificationwindow',
            index=models.Index(fields=['workspace', 'day_scope', 'is_active'], name='svc_window_ws_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceclassificationwindow',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'hour_type', 'day_scope', 'start_minute', 'end_minute'), name='svc_window_unique_range_when_deleted_at_null'),
        ),
        migrations.AddConstraint(
            model_name='serviceclassificationwindow',
            constraint=models.CheckConstraint(condition=models.Q(('start_minute__gte', 0), ('start_minute__lt', 1440)), name='svc_window_start_minute_within_day'),
        ),
        migrations.AddConstraint(
            model_name='serviceclassificationwindow',
            constraint=models.CheckConstraint(condition=models.Q(('end_minute__gt', 0), ('end_minute__lte', 1440)), name='svc_window_end_minute_within_day'),
        ),
        migrations.AddConstraint(
            model_name='serviceclassificationwindow',
            constraint=models.CheckConstraint(condition=models.Q(('start_minute', models.F('end_minute')), _negated=True), name='svc_window_borders_must_differ'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceclassificationwindow',
            unique_together={('workspace', 'hour_type', 'day_scope', 'start_minute', 'end_minute', 'deleted_at')},
        ),
        migrations.AddIndex(
            model_name='serviceholiday',
            index=models.Index(fields=['workspace', 'is_active'], name='svc_holiday_ws_active_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceholiday',
            index=models.Index(fields=['workspace', 'date'], name='svc_holiday_ws_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceholiday',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'date', 'scope'), name='service_holiday_unique_date_scope_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceholiday',
            unique_together={('workspace', 'date', 'scope', 'deleted_at')},
        ),
        # Last, so the schema is fully in place before any row is written.
        migrations.RunPython(backfill_priorities_and_seed_windows, clear_windows),
    ]
