# Generated by Django 5.2.15 on 2026-08-06 15:02
#
# Hand-edited to add the pre-flight check before the constraint.
#
# Validated by hand, because pytest.ini sets --nomigrations and the suite builds its
# schema from the models -- a broken migration would not fail a single test.
#
# THE BACK-FILL IS THE `AddField` DEFAULT, and that is deliberate rather than lazy.
# Adding a NOT NULL column with a default makes PostgreSQL write 'updated' into every
# existing row in one statement, which is exactly the intended back-fill. A separate
# RunPython would be a second statement doing the same work.
#
# And 'updated' is a fact, not a guess: before this column existed, every row in this
# table was written by `record_config_activity`, which is only ever called from
# `save_with_config_activity` on an already-saved instance. Creation and deletion had no
# code path at all, so no historical row can be either.
#
# THE PRE-FLIGHT CHECK exists because the new constraint requires old_value and new_value
# to be present on an `updated` row, and both columns are nullable. Every field tracked so
# far is a non-nullable model field, so no historical row should violate it -- but "should"
# is not "does", and a CheckConstraint that fails to apply produces a Postgres error deep
# in a migration with no indication of which rows are at fault. The check names them.

from django.db import migrations, models


def refuse_incoherent_historical_rows(apps, schema_editor):
    """Fail early, and legibly, if any existing row cannot satisfy the new constraint.

    Deliberately raises instead of repairing. The only repair available would be to invent
    a value for old_value or new_value, and writing a fabricated value into a financial
    audit trail to get a migration to pass is worse than stopping and asking a human.
    """
    ServiceConfigActivity = apps.get_model("db", "ServiceConfigActivity")

    incoherent = ServiceConfigActivity.objects.filter(
        models.Q(field_name__isnull=True) | models.Q(old_value__isnull=True) | models.Q(new_value__isnull=True)
    )

    count = incoherent.count()

    if not count:
        return

    sample = list(incoherent.values_list("id", "entity_name", "field_name")[:5])

    raise RuntimeError(
        f"{count} service_config_activities row(s) cannot satisfy "
        "svc_cfg_activity_shape_matches_verb, which requires field_name, old_value and "
        "new_value on every 'updated' row.\n"
        f"First few: {sample}\n"
        "Every historical row came from ChangeTrackerMixin on a non-nullable field, so "
        "this is unexpected. Inspect these rows and decide whether they are genuine "
        "edits with a missing side (in which case the constraint needs relaxing) or "
        "corrupt (in which case they need correcting by hand). This migration will not "
        "invent values for an audit trail."
    )


def noop_reverse(apps, schema_editor):
    """Nothing to undo: the check wrote nothing."""


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_service_calendar_and_hour_type_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfigactivity',
            name='verb',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], default='updated', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceconfigactivity',
            name='field_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        # Between the column changes and the constraint, so it can see the back-filled
        # verb and report on real data rather than on a half-migrated table.
        migrations.RunPython(refuse_incoherent_historical_rows, noop_reverse),
        migrations.AddConstraint(
            model_name='serviceconfigactivity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('field_name__isnull', False), ('new_value__isnull', False), ('old_value__isnull', False), ('verb', 'updated')), models.Q(('field_name__isnull', True), ('new_value__isnull', False), ('old_value__isnull', True), ('verb', 'created')), models.Q(('field_name__isnull', True), ('new_value__isnull', True), ('old_value__isnull', False), ('verb', 'deleted')), _connector='OR'), name='svc_cfg_activity_shape_matches_verb'),
        ),
    ]
