# Generated by Django 5.2.15 on 2026-08-07 03:36

import django.db.models.deletion
import plane.db.mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0130_service_pricing_and_amounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMemberPermission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('can_manage_others', models.BooleanField(default=False)),
                ('can_delegate', models.BooleanField(default=False)),
                ('can_reassign_author', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_permissions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Service Member Permission',
                'verbose_name_plural': 'Service Member Permissions',
                'db_table': 'service_member_permissions',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['workspace', 'member'], name='svc_member_perm_ws_member_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'member'), name='svc_member_perm_unique_when_deleted_at_null')],
                'unique_together': {('workspace', 'member', 'deleted_at')},
            },
            bases=(plane.db.mixins.ChangeTrackerMixin, models.Model),
        ),
    ]
