# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

"""Phase 9, D54. An alert dismissal may target an allowance, not only a period.

Phase 5 shipped allowance alerts that could not be dismissed, and named it as debt owed
by this phase: ``ServiceContractAlertDismissal.period`` was mandatory, so there was
nowhere to record the acknowledgement of an allowance alert.

The fix follows **D29 literally** -- a nullable pair with the exclusivity in DDL -- because
``ServiceHourLedgerEntry`` already solved the identical "period or allowance, never both"
problem that way, in the same module. A sibling table would have been a second solution to
one problem.

**Written by hand rather than autogenerated, and that is the point.** The autodetector
cannot infer a model rename non-interactively, so it proposed ``CreateModel`` +
``DeleteModel``, which drops ``service_contract_alert_dismissals`` and every dismissal in
it. ``RenameModel`` is a state-only operation here: the old model already declared
``db_table = "service_contract_alert_dismissals"`` and the new one keeps it, so Django
skips the ``ALTER TABLE ... RENAME`` and no rows move.

Numbered 0132 with 0131 left free for the delegation phase, which was in flight in a
parallel session and has since merged -- hence the dependency on it rather than on 0130.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0131_service_member_permission")]

    operations = [
        # State only -- `db_table` is unchanged, so no table is renamed and no data moves.
        # The class name is what changes: the table is about to hold rows with no contract
        # anywhere in them, and a name saying "Contract" would send the next reader looking
        # for a foreign key that is not there.
        migrations.RenameModel(
            old_name="ServiceContractAlertDismissal",
            new_name="ServiceAlertDismissal",
        ),
        # The human-readable names follow the class. State only.
        migrations.AlterModelOptions(
            name="servicealertdismissal",
            options={
                "ordering": ("-dismissed_at",),
                "verbose_name": "Service Alert Dismissal",
                "verbose_name_plural": "Service Alert Dismissals",
            },
        ),
        # Dropped before `period` becomes nullable. Leaving it in place would keep a unique
        # index that stops protecting anything once NULLs are allowed -- in Postgres NULLs
        # are distinct inside a unique index -- and it is replaced below by two conditional
        # ones that each cover only the rows targeting their own entity.
        migrations.RemoveConstraint(
            model_name="servicealertdismissal",
            name="service_alert_dismissal_unique_per_period_when_deleted_at_null",
        ),
        # Emptied before `allowance` is added, then set to its new value at the end. Doing
        # it in one step would ask Postgres to build an index over a column that does not
        # exist yet.
        migrations.AlterUniqueTogether(
            name="servicealertdismissal",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="servicealertdismissal",
            name="period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="alert_dismissals",
                to="db.servicecontractperiod",
            ),
        ),
        migrations.AddField(
            model_name="servicealertdismissal",
            name="allowance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="alert_dismissals",
                to="db.serviceissueallowance",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="servicealertdismissal",
            unique_together={("period", "allowance", "alert_code", "deleted_at")},
        ),
        migrations.AddConstraint(
            model_name="servicealertdismissal",
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted_at__isnull=True, period__isnull=False),
                fields=("period", "alert_code"),
                name="service_alert_dismissal_unique_per_period_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicealertdismissal",
            constraint=models.UniqueConstraint(
                condition=models.Q(allowance__isnull=False, deleted_at__isnull=True),
                fields=("allowance", "alert_code"),
                name="service_alert_dismissal_unique_per_allowance_when_deleted_at_null",
            ),
        ),
        # D54. Exactly one target: never both, and never neither. "Never neither" is the
        # half that is easy to forget, and the one that would let an orphan dismissal
        # silence nothing while still looking like a record of somebody's decision.
        migrations.AddConstraint(
            model_name="servicealertdismissal",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(allowance__isnull=True, period__isnull=False)
                    | models.Q(allowance__isnull=False, period__isnull=True)
                ),
                name="service_alert_dismissal_has_exactly_one_target",
            ),
        ),
        migrations.AddIndex(
            model_name="servicealertdismissal",
            index=models.Index(
                fields=["allowance", "alert_code"], name="svc_alert_dismissal_allow_idx"
            ),
        ),
    ]
