# Generated by Django 5.2.15 on 2026-08-08 18:44

from django.db import migrations, models

#: The value upstream shipped as the default, and therefore the value every profile created
#: before this migration carries unless somebody went and changed it.
UPSTREAM_DEFAULT = "en"

#: Where this fork is spoken.
FORK_DEFAULT = "pt-BR"


def language_to_pt_br(apps, schema_editor):
    """Move the profiles still on the upstream default onto this fork's language.

    **Only the rows still on ``en``.** A profile someone deliberately switched to another
    language -- French, Japanese -- is a choice, and a migration that overwrote it would be
    the migration deciding something the user already decided.

    **The one case this cannot get right, stated plainly:** a user who deliberately chose
    English is indistinguishable from a user who never chose anything, because the value is
    the same and nothing records which of the two happened. Both move to ``pt-BR``. That is
    accepted rather than worked around -- the alternatives are guessing from
    ``is_onboarded``, which the seed sets for everybody, or leaving every pre-existing
    account on a language this fork does not serve. The affected user changes it back in one
    click, in a screen that is now in their language either way.

    Tolerant of what the real database has: no assumption that any row exists, and no
    assumption about which other languages are present. ``update()`` on a filtered queryset
    rather than a loop, so it is one statement regardless of row count.
    """
    Profile = apps.get_model("db", "Profile")

    moved = Profile.objects.filter(language=UPSTREAM_DEFAULT).update(language=FORK_DEFAULT)

    if moved:
        print(f"  profiles moved from {UPSTREAM_DEFAULT} to {FORK_DEFAULT}: {moved}")


def language_back_to_en(apps, schema_editor):
    """Deliberately a no-op on the data. The forward direction is lossy.

    Reversing it would mean setting every ``pt-BR`` profile back to ``en``, which cannot
    distinguish the rows this migration moved from the rows that were already ``pt-BR``
    because a user chose it -- the demo scenario's accounts, among others, were switched by
    hand before this migration existed. So a "reversal" would silently destroy real choices
    to undo a change whose only cost is one click.

    The schema half **does** reverse: ``AlterField`` puts the column default back. That is
    what makes this migration reversible in the sense that matters -- ``migrate db 0133``
    runs clean and leaves the model definition consistent -- and the data half is documented
    as one-way rather than pretending otherwise.
    """
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0133_service_issue_requester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="language",
            field=models.CharField(default="pt-BR", max_length=255),
        ),
        migrations.RunPython(language_to_pt_br, language_back_to_en),
    ]
