# Generated by Django 5.2.15 on 2026-08-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0134_profile_language_defaults_to_pt_br'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='intake_auto_accept',
            field=models.BooleanField(default=False),
        ),
    ]
